# Generated by Django 2.2.13 on 2021-10-23 13:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('id_number', models.TextField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default=254, max_length=128, region=None)),
            ],
        ),
    ]
