# Generated by Django 2.2.13 on 2021-10-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobseeker_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
