# Generated by Django 2.2.13 on 2021-10-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211024_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='id_number',
            field=models.IntegerField(),
        ),
    ]
