# Generated by Django 2.2.13 on 2021-10-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211024_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='id_number',
            field=models.CharField(max_length=8),
        ),
    ]
