# Generated by Django 2.2.13 on 2021-11-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211024_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='company',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='What_are_you',
            field=models.CharField(choices=[('CC', 'Content creater'), ('CS', 'Youtuber')], default='RAKS', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
