# Generated by Django 2.2.13 on 2021-11-05 13:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211105_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=8)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('What_are_you', models.CharField(choices=[('CC', 'Content creater'), ('CS', 'Youtuber')], default='RAKS', max_length=200)),
                ('Which_educational_or_tutorial_content_are_you_interested_in', models.CharField(choices=[('MATH', 'MATHEMATICS'), ('CS', 'COMPUTER_SCIENCE'), ('ENG', 'ENGINEERING'), ('ECON', 'ECONOMICS'), ('MED', 'MEDICINE'), ('CRAFT', 'CRAFTS')], default='MATH', max_length=200)),
                ('terms', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='JobSeeker',
        ),
    ]
