# Generated by Django 2.2.13 on 2021-11-09 09:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211105_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('request_for_which_type_of_content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='What_are_you',
            field=models.CharField(choices=[('CC', 'Content creater'), ('Y', 'Youtuber')], default='CC', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Which_educational_or_tutorial_content_are_you_interested_in',
            field=models.CharField(choices=[('MATH', 'MATHEMATICS'), ('CS', 'COMPUTER_SCIENCE'), ('ENG', 'ENGINEERING'), ('ECON', 'ECONOMICS'), ('MED', 'MEDICINE'), ('MR', 'REVIEWING MOVIES')], default='CS', max_length=200),
        ),
    ]
