# Generated by Django 2.2.13 on 2021-11-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211109_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentrequestmodel',
            old_name='names',
            new_name='full_names',
        ),
    ]
