# Generated by Django 2.2.13 on 2021-11-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211109_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentrequestmodel',
            old_name='full_names',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='contentrequestmodel',
            old_name='mobile_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='contentrequestmodel',
            old_name='request_for_which_type_of_content',
            new_name='type_here_the_type_of_content_you_want',
        ),
    ]
