# Generated by Django 2.2.13 on 2021-11-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211109_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Which_educational_or_tutorial_content_are_you_interested_in',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='Which_educational_or_tutorial_content_can_you_create_or_looking_for',
            field=models.CharField(choices=[('MATH', 'MATHEMATICS'), ('CS', 'COMPUTER_SCIENCE'), ('ENG', 'ENGINEERING'), ('ECON', 'ECONOMICS'), ('MED', 'MEDICINE'), ('MR', 'REVIEWING MOVIES')], default='MR', max_length=200),
        ),
    ]
